name: Jobs condition testing
on: 
  workflow_dispatch:
    inputs:
        infra_deploy:
            required: true
            type: boolean
        code_deploy:
            required: false
            type: boolean

jobs:
  plan:
    runs-on: ubuntu-latest
    
    steps:
        - name:  Job1
          run: |
            echo job1
        
  apply:
    needs: plan
    runs-on: ubuntu-latest

    steps:
        - name:  Job2 
          run: |
            echo job2 

  get-vars:
    needs: apply
    runs-on: ubuntu-latest

    steps:
        - name:  Job2 
          run: |
            echo job2

  code-deploy:
    needs: get-vars
    runs-on: ubuntu-latest

    steps:
        - name:  Job3
          run: |
            echo job3

