name: Jobs condition testing
on: 
  workflow_dispatch:
    inputs:
        infra_deploy:
            required: true
            type: boolean
        code_deploy:
            required: false
            type: boolean

jobs:
  plan:
    if: ${{ inputs.infra_deploy}}
    runs-on: ubuntu-latest
    
    steps:
        - name:  Job1
          run: |
            echo job1
        
  apply:
    needs: plan
    runs-on: ubuntu-latest

    steps:
        - name:  Job2 
          run: |
            echo job2 

  get-vars:
    needs: [ plan, apply ] 
    runs-on: ubuntu-latest
    if: |
        always() &&
        (needs.apply.result == 'success' || needs.apply.result == 'skipped')
    #   (needs.plan.result == 'success' || needs.plan.result == 'skipped') && 
    #   (needs.apply.result == 'success' || needs.apply.result == 'skipped') && 
    #   !(needs.plan.result == 'skipped' && needs.apply.result == 'skipped')
    steps:
        - name:  Job2 
          run: |
            echo job2

  code-deploy:
    needs: get-vars
    runs-on: ubuntu-latest

    steps:
        - name:  Job3
          run: |
            echo job3

