name: Jobs condition testing
on: 
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    
    steps:
        - name:  Job1
          run: |
            echo job1
        
  build-job2:
    needs: build-job
    runs-on: ubuntu-latest

    steps:
        - name:  Job2 
          run: |
            echo job2 

  build-job3:
    needs: build-job2
    runs-on: ubuntu-latest

    steps:
        - name:  Job3
          run: |
            echo job3

